name: Release process
run-name: Release in progress
on:
  push:
    branches:
      - "master"
    tags:
      - v[0-9]+
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "you have created a release tag"
