name: Prepare release
run-name: Preparing release
on:
  push:
    tags:
      - v[0-9]+

env:
  user_name: ${{ secrets.USER_NAME }}
  user_EMAIL: ${{ secrets.USER_EMAIL }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Create hotfix branch and issue
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: ./scripts/prepare-release.sh ${{  github.ref_name }} ${{  github.actor }}
