name: Prepare release
run-name: Preparing release
on:
  push:
    tags:
      - v[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Create hotfix branch and issue
        run: ./scripts/prepare-release.sh ${{  github.ref_name }} ${{  github.author }}
