name: Run tests for pull request
run-name: Running tests for ${{ github.event.pull_request.title }} for commit ${{ github.event.pull_request.head.sha }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install npm packages
        run: npm ci
      - name: Install puppeteer
        run: npx playwright install --with-deps chromium
  run-unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  run-e2e-tests:
    needs: [install-dependencies, run-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - run: npm run e2e
