name: Run tests for pull request
run-name: Running tests for ${{ github.event.pull_request.title }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install npm packages
        run: npm ci
      - run: npm run test-ci
      - name: Install puppeteer
        run: npx playwright install --with-deps chromium
      - run: npm run e2e-ci
